### ISSUE TITLE
Using string arrays does not work?

### ISSUE THREAD

**Issue by muuvmuuv** [acuminous/power-merge#22]
I have two string arrays I want to merge but with more control of the merge process. It seems that pm cannot handle arrays of string only objects, isn't it? Would be great to be able to use string arrays, so I can apply some more testing for it. My use-case is a bit heavy, so a simple merge from lodash e.g. would not work.

**Comment by cressie176** [comment]
Hi @muuvmuuv, can you provide an example of input and desired output please?

**Comment by muuvmuuv** [comment]
It is a little difficult to explain tbh. I will try to, but we might have already found a solution.

We have a group of sequences that should be merged into one, but the order should be kept:

```json
[
  ["A", "B", "C", "D"]
  ["C", "F", "D"]
  ["A", "A", "D", "D", "A"]
]
```

this should become:

```json
["A", "A", "B", "C", "F", "D", "D", "A"]
```

We're iterating over each sequence one after the other and try to find the closed match and will skip or insert the rest of the sequence. For the first sequence "A B C D" we should add all to take it as a ref for the others. Then "C F D" we see C matches and because order matters the "F" must be inserted between this previous and next match.

**Comment by cressie176** [comment]
It does sound difficult to explain! I think I understand you with how ["A", "B", "C", "D"] and ["C", "F", "D"] should be merged, i.e. the "C" in the first array would be replaced by the elements of the second array, resulting in  ["A", "B", "C", "F", "D", "D"] however I don't see how applying the third array ["A", "A", "D", "D", "A"] leads to the outcome ["A", "A", "B", "C", "F", "D", "D", "A"].

Nevertheless, when merging arrays you typically want to do one of the following things...

* Pick one of the arrays and discard the other
* Concatenate both arrays (keeping duplicates)
* Take the union of both arrays (discarding duplicates)
* Overwrite one array with the other, but don't truncate, e.g. [["A", "B"], ["X", "Y", "Z"]] => ["A", "B", "Z"]
* Recursively merge them by iterating through (not particularly useful for arrays of strings)

In your case it sounds like you need a [custom power-merge command](https://github.com/acuminous/power-merge#custom-commands). The command would two arrays, work out whether to splice in the second.

**Comment by cressie176** [comment]
Something like...

```js
const debug = require('debug')('power-merge:commands:insertArray');

module.exports = function __insertArray() {

  return function _insertArray() {

    return function insertArray(facts) {

      debug('facts: %o', facts);
      
      // facts.a.value is the first array
      // facts.b.value is the second array
           
      const index = facts.a.value.indexOf(facts.b.value[0]); // Find where the second array should be inserted into the first
      const clone = [ ...facts.a.value ]; // Copy a.value as we're mutating
      if (index >= 0) clone[index] = facts.b.value; // replace the matched string with the second array
      const result = [].concat(...clone); // Flatten the nested array
      
      debug('return: %o', result);
      return result;
    };
  };
};
```

Once defined you would use your command as follows...

```js
const rules = [
  {
    when: and([
      eq('a.type', 'Array'),
      eq('b.type', 'Array'),
    ]),
    then: insertArray(),
  },
];
```

**Comment by muuvmuuv** [comment]
Thanks for the effort! I won't try it now because we are skipping this part in the project and pick it up later in the queue. For now, I will close it.
